
["Stone Generation"]
	#Sets average plate area in chunks; Recommended Default is 64
	#Range: 16 ~ 2048
	"Fault Size" = 128
	#Sets average stone region area in chunks; Recommended Default is 128
	#Range: 16 ~ 2048
	"Region Size" = 512
	#Sets general difference between regions; Recommended Default is 0.50
	#Range: 0.0 ~ 1.0
	"Regional Variation" = 0.5
	#Sets the degree of range for fault shift; Recommended Default is 0.20
	#Range: 0.0 ~ 1.0
	"Fault Variation" = 0.2

